name: Update GitHub Stats

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate GitHub Readme Stats
        uses: abhisheknaiidu/awesome-github-profile-readme@main
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "📊 Update GitHub stats" || exit 0
          git push
