name: Update GitHub Stats

on:
  schedule:
    - cron: '0 6 * * *'  # Executa todo dia às 6h UTC
  workflow_dispatch:      # Permite executar manualmente
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Update README with latest stats
        run: |
          echo "🔄 Atualizando estatísticas..."
          # Este passo vai apenas forçar a atualização
          date >> update.log
          echo "📊 Estatísticas atualizadas em: $(date)" >> update.log
          
      - name: Generate GitHub Stats Cards
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_SHORT_INFO: "False"
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "📈 Atualizar estatísticas do GitHub"
          git push
